### ISSUE TITLE
Cannot Make Stamina potion 

### ISSUE THREAD

**Issue by WinAllDay11** [ekmillard/Edgeville-Beta#17]
so you need amylase crystal & super energy potion, when i spawn the amylase crystal it comes as NULL Into my inventory 
Nothing Interesting happens when i use it on the super energy.

https://gyazo.com/b45023192f9bf2d61e19ad485cd459d9

**Comment by agroebe** [comment]
Not an actual issue. Just tested and it works fine.

You're probably spawning the wrong amylase crystal ID
