### ISSUE TITLE
one of the obstacles @ Barbarian outpost agility course looks glitched.

### ISSUE THREAD

**Issue by Huncho187** [ekmillard/Edgeville-Beta#25]
![image](https://user-images.githubusercontent.com/130640619/231788958-91ee2688-4add-4599-af74-71bf9cde811c.png)

**Comment by agroebe** [comment]
This is due to enabling the "skybox" plugin on RuneLite. turn that off and it will look normal.

TODO: check if runelite skybox has an exception for this obj?
