### ISSUE TITLE
guam tar herblore

### ISSUE THREAD

**Issue by WinAllDay11** [ekmillard/Edgeville-Beta#6]
so you need a guam leaf & swamp tar to create a guam tar,
nothing interesting happens.

https://gyazo.com/cde510163257d68130e6f775101ab68b

**Comment by WinAllDay11** [comment]
also the guthix balance potion doesn't work, im not really sure if these potions are needed so im going to leave the comments in one section

**Comment by WinAllDay11** [comment]
also can't create marrentill tar

**Comment by ekmillard** [comment]
> so you need a guam leaf & swamp tar to create a guam tar, nothing interesting happens.
> 
> https://gyazo.com/cde510163257d68130e6f775101ab68b

Wasn't broken just needed 15 tar and p&m.

**Comment by ekmillard** [comment]
> also the guthix balance potion doesn't work, im not really sure if these potions are needed so im going to leave the comments in one section

Not needed at the moment due to it being a quest item.

**Comment by ekmillard** [comment]
> also can't create marrentill tar & tarromin tar & harralander tar

You can check out there wiki and make sure you have all the required items in order to create them.

**Comment by ekmillard** [comment]
> magic essence potion doesn't work at all, ive spawned gorak claw powder still didnt work
> 
> Also cant ground the claws as shown down below https://gyazo.com/6615a89dbba43d14809522cc40374eed

Another quest potion don't need atm.
